name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify to Teams Channel
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: '&#x1F680 デプロイ開始 [本番環境]'
          summary: 'デプロイ開始'
          text: '本番環境へのデプロイを開始しました '
          theme_color: 007bff

      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          yarn
          yarn generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs

      - name: Notify to Teams Channel
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: '&#x1F389 デプロイ完了'
          summary: 'デプロイ完了'
          text: 'デプロイが完了しました'
          theme_color: 28a745

